esphome:
  name: upsa-monitor-2
  friendly_name: UPS-Monitor-2
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini

i2c:
  scan: True

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    max_current: 0.8192A
    # adc time used for both, Bus Voltage and Shunt Voltage
    adc_time: 140us
    adc_averaging: 128
    update_interval: 2s
    current:
      name: "INA226 Current"
    power:
      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
      filters:
        calibrate_linear:
          method: least_squares
          datapoints:
            # Map 0.0 (from sensor) to 1.0 (true value)
            - 3.65 -> 3.59
            - 13.53 -> 13.33