substitutions:
  BRIGHTNESS: "80"
  THERMOSTAT_ENTITY: climate.termostat
  COLOR_1: "0x23f337"
  COLOR_2: "0x2b9a36"
  
esphome:
  name: cyd-lvgl
  friendly_name: CYD_LVGL
  on_boot:
  - priority: 600
    then:
      - light.turn_on:
          id: backlight
          brightness: ${BRIGHTNESS}%

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Cyd-Lvgl Fallback Hotspot"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: homeassistant
    id: watt_power
    entity_id: sensor.breaker_phase_a_power
    accuracy_decimals: 1
    on_value:
      then:
        - lvgl.label.update:
            id: watt_label
            text:
              format: "%.0fW"
              args: [ 'x' ]

  - platform: homeassistant
    id: thermostat_set
    entity_id: $THERMOSTAT_ENTITY
    attribute: temperature
    unit_of_measurement: "째C"
    on_value:
      - lvgl.label.update:
          id: temp_set
          text:
            format: "%.1f째C"
            args: [ 'x' ]


  - platform: homeassistant
    id: voltage_sensor
    entity_id: sensor.voltage_corrected
    unit_of_measurement: "V"
    on_value:
      - lvgl.indicator.update:
          id: volt_needle
          value: !lambda "return x;"
      - lvgl.label.update:
          id: gauge_label
          text:
            format: "%.0fV"
            args: [ 'x' ]

  - platform: homeassistant
    id: charger_sensor
    entity_id: sensor.obksmartplug05_power
    unit_of_measurement: "W"
    on_value:
      - lvgl.bar.update:
          id: charger_bar
          value: !lambda |-
            if(x==0) {
              return 0;
            } else {
              return 100-(x*1.84);
            }      

  - platform: homeassistant
    id: thermostat_now
    entity_id: $THERMOSTAT_ENTITY
    attribute: current_temperature
    unit_of_measurement: "째C"
    on_value:
      - lvgl.label.update:
          id: temp_now
          text:
            format: "%.1f째C"
            args: [ 'x' ]

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_OFF

spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm

display:
  - platform: ili9xxx
    model: ILI9342
    invert_colors: false
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    transform:
      mirror_y: true
    color_palette: 8BIT
    color_order: rgb
    auto_clear_enabled: false
    update_interval: never

touchscreen:
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  threshold: 400
  calibration:
    x_min: 240
    x_max: 3750
    y_min: 290
    y_max: 3750
  transform:
    swap_xy: true
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );      

font:
  - file: "fonts/BebasNeue-Regular.ttf"
    id: font_1
    size: 50
    bpp: 4

  - file: "fonts/BebasNeue-Regular.ttf"
    id: font_2
    size: 40
    bpp: 4

  - file: "fonts/BebasNeue-Regular.ttf"
    id: font_3
    size: 30
    bpp: 4

  - file: "fonts/BebasNeue-Regular.ttf"
    id: font_4
    size: 20
    bpp: 4

  - file: "fonts/BebasNeue-Regular.ttf"
    id: font_5
    size: 15
    bpp: 4

  - file: "fonts/Rio_font.ttf"
    id: rfont
    size: 42
    bpp: 4

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kyiv
    on_time:
      - cron: '* * * * * *'
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: local_time
          text: !lambda |-
            char buff[10] = "-";
            auto time = id(sntp_time).now();
            if (time.is_valid())
              sprintf(buff, "%02d:%02d", time.hour, time.minute);
            return buff;
      - lvgl.bar.update:
          id: bar_seconds
          value: !lambda |-
            auto time = id(sntp_time).now();
            if (time.is_valid())
              return time.second;

lvgl:
  buffer_size: 25%
  bg_color: 0x000000
  scrollbar_mode: "OFF"
  scrollable: false
  widgets:
    - obj:
        id: main_bg
        bg_color: $COLOR_1
        bg_opa: 100%
        bg_grad_color: $COLOR_2
        bg_main_stop: 0
        bg_grad_stop: 0
        bg_grad_dir: VER
        border_width: 0
        width: 320
        height: 240
        align: CENTER

    - obj:
        id: bgfill
        width: 306
        height: 226
        align: CENTER
        bg_color: 0x101010
        bg_opa: 100%
        border_width: 0

    - label:
        align: TOP_LEFT
        id: local_time
        text: "--:--"
        height: 56
        text_font: font_1
        text_color: WHITE
        translate_x: 10
        translate_y: 7
        widgets:
          - bar:
              align: BOTTOM_LEFT
              translate_x: 7
              id: bar_seconds
              height: 5
              width: 78
              min_value: 0
              max_value: 60
              mode: NORMAL
              value: 30
              bg_color: 0x292929
              bg_opa: 100%
              indicator:
                bg_color: $COLOR_1
                bg_opa: 100%

    - spinner:
        id: spinner
        align: TOP_RIGHT
        x: -15
        y: 13
        width: 50
        height: 50
        arc_length: 120deg
        spin_time: 3s
        arc_color: 0x292929
        arc_width: 5
        arc_rounded: true
        indicator:
          arc_color: $COLOR_1
          arc_width: 5
          arc_opa: 100%
          arc_rounded: true
        widgets:
          - label:
              align: CENTER
              text: 'R'
              text_font: rfont
              text_color: WHITE
              translate_x: 2
              translate_y: 4

    - obj:
        id: wattage_bg
        width: 125
        height: 50
        x: 15
        y: 14
        align: TOP_MID
        radius: 3
        bg_color: 0xFFFFFF
        bg_opa: 100%
        border_width: 0
        scrollbar_mode: "OFF"
        scrollable: false
        widgets:
          - obj:
              x: -10
              y: -10
              width: 10
              height: 10
              align: TOP_LEFT
              bg_color: 0x2C2C2C
          - obj:
              x: 10
              y: -10
              width: 10
              height: 10
              align: TOP_RIGHT
              bg_color: 0x2C2C2C
          - obj:
              x: 10
              y: 10
              width: 10
              height: 10
              align: BOTTOM_RIGHT
              bg_color: 0x2C2C2C
          - obj:
              x: -10
              y: 10
              width: 10
              height: 10
              align: BOTTOM_LEFT
              bg_color: 0x2C2C2C
          - label:
              id: watt_label
              #x: -6
              y: 2
              align: CENTER
              text_align: CENTER
              text: "----W"
              text_font: font_2
              text_color: 0x101010

    - obj:
        width: 134
        height: 90
        x: -77
        y: 8
        align: CENTER
        radius: 10
        bg_color: $COLOR_1
        bg_grad_color: $COLOR_2
        bg_grad_dir: VER
        border_width: 0
        scrollable: false
        scrollbar_mode: "OFF"
        widgets:
          - label:
              y: -7
              align: TOP_MID
              text: "TEPMOCTAT"
              text_color: 0xFFFFFF
              text_font: font_3
              radius: 3
              bg_color: 0x101010
              bg_opa: 100%
              pad_left: 7
              pad_right: 7
              pad_top: 2
          - button:
              width: 33
              height: 33
              x: -6
              y: 6
              align: BOTTOM_LEFT
              radius: 20
              bg_color: 0xFFFFFF
              widgets:
                - label:
                    align: CENTER
                    x: 1
                    y: 1
                    text: "-"
                    text_color: 0x101010
                    text_font: font_3
              on_click:
                - homeassistant.service:
                    service: climate.set_temperature
                    data:
                      entity_id: $THERMOSTAT_ENTITY
                    data_template:
                      temperature: '{{ my_variable }}'
                    variables:
                      my_variable: |-
                        return id(thermostat_set).state - 0.5;
          - button:
              width: 33
              height: 33
              x: 6
              y: 6
              align: BOTTOM_RIGHT
              radius: 20
              bg_color: 0xFFFFFF
              widgets:
                - label:
                    align: CENTER
                    x: 1
                    y: 1
                    text: "+"
                    text_color: 0x101010
                    text_font: font_3
              on_click:
                - homeassistant.service:
                    service: climate.set_temperature
                    data:
                      entity_id: $THERMOSTAT_ENTITY
                    data_template:
                      temperature: '{{ my_variable }}'
                    variables:
                      my_variable: |-
                        return id(thermostat_set).state + 0.5;
          - label:
              id: temp_now
              y: -3
              align: BOTTOM_MID
              text: "--.-"
              text_color: 0x101010
              text_font: font_4
          - label:
              id: temp_set
              y: 11
              align: BOTTOM_MID
              text: "--.-"
              text_color: 0x101010
              text_font: font_5

    - slider:
        id: bright_slider
        value: ${BRIGHTNESS}
        width: 286
        height: 15
        x: 0
        y: -26
        align: BOTTOM_MID
        bg_color: 0x292929
        indicator:
          bg_color: $COLOR_1
          bg_grad_color: $COLOR_2
          bg_grad_dir: HOR
        knob:
          bg_color: 0xFFFFFF
        on_release:
          - light.turn_on:
              id: backlight
              brightness: !lambda return float(x)/100;

    - meter:
        width: 90
        height: 90
        align: RIGHT_MID
        x: -68
        y: 9
        scales:
          range_from: 190
          range_to: 260
          angle_range: 240
          rotation: 150
          ticks:
            count: 25
            length: 18
            width: 2
          indicators:
            - line:
                id: volt_needle
                width: 3
                color: 0x101010
                r_mod: -4
            - tick_style:
                start_value: 190
                end_value: 260
                color_start: $COLOR_2
                color_end: $COLOR_1
        widgets:
          - label:
              id: gauge_label
              align: CENTER
              y: 26
              text: "---V"
              text_font: font_4
              text_color: 0x101010

    - obj:
        scrollbar_mode: "OFF"
        scrollable: false
        width: 18
        height: 10
        x: -28
        y: -22
        align: RIGHT_MID
        radius: 3
        bg_color: 0x292929
        border_width: 0

    - obj:
        scrollbar_mode: "OFF"
        scrollable: false
        width: 38
        height: 62
        x: -18
        y: 10
        align: RIGHT_MID
        radius: 4
        bg_color: 0x292929
        border_width: 0
        widgets:
          - bar:
              id: charger_bar
              width: 30
              height: 54
              align: CENTER
              radius: 3
              bg_color: 0x101010
              min_value: 0
              max_value: 100
              value: 20
              indicator:
                radius: 3
                bg_color: $COLOR_1
                bg_opa: 100%
              on_click:
                - homeassistant.action:
                    action: switch.toggle
                    data:
                      entity_id: switch.obksmartplug05_0
